# Generated by Django 6.1.1 on 2026-09-15 10:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'client',
                'ordering': ['-dateCreation'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomService', models.CharField(max_length=150)),
                ('typeService', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modeTarification', models.CharField(blank=True, max_length=50, null=True)),
                ('uniteFacturation', models.CharField(blank=True, max_length=50, null=True)),
                ('statut', models.CharField(default='Actif', max_length=20)),
            ],
            options={
                'db_table': 'service',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('Accueil', 'Accueil'), ('Admin', 'Admin'), ('Technicien', 'Technicien')], default='Accueil', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'utilisateur',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCommande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('En cours', 'En cours'), ('Validée', 'Validée'), ('Archivée', 'Archivée'), ('Annulée', 'Annulée')], default='En cours', max_length=50)),
                ('observation', models.TextField(blank=True, null=True)),
                ('montantTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('client', models.ForeignKey(db_column='idClient', on_delete=django.db.models.deletion.RESTRICT, related_name='commandes', to='radio_app.client')),
                ('utilisateur', models.ForeignKey(db_column='idUtilisateur', on_delete=django.db.models.deletion.RESTRICT, related_name='commandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commande',
                'ordering': ['-dateCommande'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeDocument', models.CharField(choices=[('Papier', 'Document papier'), ('Numerique', 'Fichier numérique')], default='Papier', max_length=50)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(db_column='idCommande', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='radio_app.commande')),
            ],
            options={
                'db_table': 'document',
                'ordering': ['-dateCreation'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroFacture', models.CharField(max_length=50, unique=True)),
                ('dateFacture', models.DateTimeField(auto_now_add=True)),
                ('montantTotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('Non payé', 'Non payé'), ('Payé', 'Payé')], default='Non payé', max_length=50)),
                ('commande', models.OneToOneField(db_column='idCommande', on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='radio_app.commande')),
            ],
            options={
                'db_table': 'facture',
                'ordering': ['-dateFacture'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('quantite', models.IntegerField(default=1)),
                ('prixUnitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('commande', models.ForeignKey(db_column='idCommande', on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='radio_app.commande')),
                ('service', models.ForeignKey(db_column='idService', on_delete=django.db.models.deletion.RESTRICT, related_name='lignes', to='radio_app.service')),
            ],
            options={
                'db_table': 'ligne_commande',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FichierAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomFichier', models.CharField(max_length=255)),
                ('cheminOrdinateur', models.CharField(blank=True, max_length=500, null=True)),
                ('cheminPAD', models.CharField(blank=True, max_length=500, null=True)),
                ('format', models.CharField(default='mp3', max_length=10)),
                ('taille', models.BigIntegerField(blank=True, null=True)),
                ('duree', models.IntegerField(blank=True, null=True)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('Disponible', 'Disponible'), ('Transféré', 'Transféré'), ('En attente', 'En attente'), ('Échec', 'Échec')], default='Disponible', max_length=50)),
                ('ligne', models.ForeignKey(db_column='idLigne', on_delete=django.db.models.deletion.CASCADE, related_name='fichiersAudio', to='radio_app.lignecommande')),
            ],
            options={
                'db_table': 'fichier_audio',
                'ordering': ['-dateCreation'],
            },
        ),
        migrations.CreateModel(
            name='Programmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDiffusion', models.DateField()),
                ('heureDiffusion', models.TimeField()),
                ('ordreDiffusion', models.IntegerField(default=1)),
                ('statut', models.CharField(choices=[('Programmé', 'Programmé'), ('Diffusé', 'Diffusé'), ('Expiré', 'Expiré'), ('Échec', 'Échec')], default='Programmé', max_length=50)),
                ('fichierAudio', models.ForeignKey(db_column='idFichierAudio', on_delete=django.db.models.deletion.CASCADE, related_name='programmations', to='radio_app.fichieraudio')),
            ],
            options={
                'db_table': 'programmation',
                'ordering': ['dateDiffusion', 'heureDiffusion', 'ordreDiffusion'],
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
                ('duree', models.IntegerField(default=0)),
                ('unite', models.CharField(blank=True, max_length=20, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(default='Actif', max_length=20)),
                ('service', models.ForeignKey(db_column='idService', on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='radio_app.service')),
            ],
            options={
                'db_table': 'tarif',
                'ordering': ['service', 'prix'],
            },
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='tarif',
            field=models.ForeignKey(db_column='idTarif', on_delete=django.db.models.deletion.RESTRICT, related_name='lignes', to='radio_app.tarif'),
        ),
    ]
