# Generated by Django 6.1.1 on 2026-09-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='dateSuppression',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='estArchive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='dateDebut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='dateFin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='heureDiffusion',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(default='Générée', max_length=50),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
