# Generated by Django 6.1.1 on 2026-09-23 14:40

import django.db.models.deletion
from django.db import migrations, models


def copier_dates_vers_commande(apps, schema_editor):
    """
    Copie dateDebut, dateFin, heureDiffusion depuis
    LigneCommande vers Commande.
    """
    LigneCommande = apps.get_model('radio_app', 'LigneCommande')
    Commande = apps.get_model('radio_app', 'Commande')

    for commande in Commande.objects.all():
        premiere_ligne = LigneCommande.objects.filter(
            commande=commande
        ).order_by('id').first()

        if premiere_ligne:
            commande.dateDebut = premiere_ligne.dateDebut
            commande.dateFin = premiere_ligne.dateFin
            commande.heureDiffusion = premiere_ligne.heureDiffusion
            commande.save(update_fields=[
                'dateDebut', 'dateFin', 'heureDiffusion'
            ])


def inverser_dates(apps, schema_editor):
    """
    Fonction inverse (rollback).
    """
    LigneCommande = apps.get_model('radio_app', 'LigneCommande')
    Commande = apps.get_model('radio_app', 'Commande')

    for commande in Commande.objects.all():
        LigneCommande.objects.filter(commande=commande).update(
            dateDebut=commande.dateDebut,
            dateFin=commande.dateFin,
            heureDiffusion=commande.heureDiffusion
        )


class Migration(migrations.Migration):

    dependencies = [
        ('radio_app', '0002_facture_datesuppression_facture_estarchive_and_more'),
    ]

    operations = [
        # ═══ ÉTAPE 1 : Ajouter les champs à Commande (nullable d'abord) ═══
        migrations.AddField(
            model_name='commande',
            name='dateDebut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='dateFin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='heureDiffusion',
            field=models.TimeField(blank=True, null=True),
        ),

        # ═══ ÉTAPE 2 : Copier les données AVANT de supprimer ═══
        migrations.RunPython(
            copier_dates_vers_commande,
            inverser_dates
        ),

        # ═══ ÉTAPE 3 : Supprimer les anciens champs de LigneCommande ═══
        migrations.RemoveField(
            model_name='lignecommande',
            name='dateDebut',
        ),
        migrations.RemoveField(
            model_name='lignecommande',
            name='dateFin',
        ),
        migrations.RemoveField(
            model_name='lignecommande',
            name='heureDiffusion',
        ),

        # ═══ ÉTAPE 4 : FichierAudio : ligne → commande ═══
        migrations.RemoveField(
            model_name='fichieraudio',
            name='ligne',
        ),
        migrations.AddField(
            model_name='fichieraudio',
            name='commande',
            field=models.ForeignKey(
                blank=True,
                db_column='idCommande',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='fichiersAudio',
                to='radio_app.commande',
            ),
        ),

        # ═══ ÉTAPE 5 : Programmation ═══
        migrations.AddField(
            model_name='programmation',
            name='dateTraitement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programmation',
            name='dateTransfert',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programmation',
            name='messageErreur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programmation',
            name='statut',
            field=models.CharField(
                choices=[
                    ('À venir', 'À venir'),
                    ('À envoyer', 'À envoyer'),
                    ('Transfert en cours', 'Transfert en cours'),
                    ('Envoyé au PAD', 'Envoyé au PAD'),
                    ('Échéance passée', 'Échéance passée'),
                    ('Archivé', 'Archivé'),
                    ('Échec', 'Échec'),
                ],
                default='À venir',
                max_length=50,
            ),
        ),
    ]