# Generated by Django 6.1.1 on 2026-09-24 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_app', '0003_remove_fichieraudio_ligne_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichieraudio',
            name='commande',
            field=models.ForeignKey(db_column='idCommande', on_delete=django.db.models.deletion.CASCADE, related_name='fichiersAudio', to='radio_app.commande'),
        ),
    ]
