# Generated by Django 6.1.1 on 2026-09-25 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio_app', '0004_alter_fichieraudio_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='heureDiffusion',
        ),
    ]
