# Generated by Django 6.1.1 on 2026-09-25 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_app', '0005_remove_commande_heurediffusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmation',
            name='commande',
            field=models.ForeignKey(blank=True, db_column='idCommande', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programmations', to='radio_app.commande'),
        ),
        migrations.AlterField(
            model_name='programmation',
            name='fichierAudio',
            field=models.ForeignKey(blank=True, db_column='idFichierAudio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programmations', to='radio_app.fichieraudio'),
        ),
    ]
