# Generated by Django 6.1.1 on 2026-10-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_app', '0006_programmation_commande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichieraudio',
            name='cheminArchive',
            field=models.CharField(blank=True, help_text='Chemin complet du fichier archivé', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fichieraudio',
            name='dateArchive',
            field=models.DateTimeField(blank=True, help_text='Date à laquelle le fichier a été archivé', null=True),
        ),
        migrations.AddField(
            model_name='fichieraudio',
            name='dateEnvoiPAD',
            field=models.DateTimeField(blank=True, help_text='Date du dernier envoi vers le PAD', null=True),
        ),
        migrations.AlterField(
            model_name='fichieraudio',
            name='statut',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Transféré', 'Transféré'), ('En attente', 'En attente'), ('Échec', 'Échec'), ('Archivé', 'Archivé')], default='Disponible', max_length=50),
        ),
    ]
